# This is a basic workflow to help you get started with Actions

name: Auth

# Controls when the workflow will run
on:
  push:
    paths:
      - 'src/airflow scripts/HitAPI.py'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CLOUD_ACCESS }}'
        
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'src/airflow scripts/HitAPI.py'
        destination: 'us-east1-twitter-data-etl-d5750cc0-bucket/dags/'
        
